# Package Overview
# Predicts crop yield (hectogram yield per hector area of crop) based on pesticides, rainfall, temparature as a feature.
package_name: crop_yield_model

# Data files
training_data_file: yield_df.csv

# Variables
target: hg_per_ha_yield

pipeline_name: crop_yield_model
pipeline_save_file: crop_yield_model_output_v

# Features
features:
  - Area
  - Item
  - Year
  - average_rain_fall_mm_per_year
  - pesticides_tonnes
  - avg_temp

    # data_in = {'Area': ['Pakistan'], 
    #            'Item': ['Wheat'], 
    #            'Year': [2009], 
    #            'average_rain_fall_mm_per_year': [494.0], 
    #            'pesticides_tonnes': [3957.61], 
    #            'avg_temp': [25.37]}

unused_fields:
  - srnum

# Features names
crop_name_var: Item
crop_country_var: Area
crop_year_var: Year
crop_pesticides_var: pesticides_tonnes
country_rain_var: average_rain_fall_mm_per_year
country_temp_var: avg_temp

# Mapping for Ordinal categorical features

crop_name_mappings:
  Maize: 0
  Potatoes: 1
  Rice: 2
  Sorghum: 3
  Soybeans: 4
  Wheat: 5
  Cassava: 6
  Sweet potatoes: 7
  Plantains and others: 8
  Yams: 9

crop_country_mappings:
  Albania: 0
  Algeria: 1
  Angola: 2
  Argentina: 3
  Armenia: 4
  Australia: 5
  Austria: 6
  Azerbaijan: 7
  Bahamas: 8
  Bahrain: 9
  Bangladesh: 10
  Belarus: 11
  Belgium: 12
  Botswana: 13
  Brazil: 14
  Bulgaria: 15
  Burkina Faso: 16
  Burundi: 17
  Cameroon: 18
  Canada: 19
  Central African Republic: 20
  Chile: 21
  Colombia: 22
  Croatia: 23
  Denmark: 24
  Dominican Republic: 25
  Ecuador: 26
  Egypt: 27
  El Salvador: 28
  Eritrea: 29
  Estonia: 30
  Finland: 31
  France: 32
  Germany: 33
  Ghana: 34
  Greece: 35
  Guatemala: 36
  Guinea: 37
  Guyana: 38
  Haiti: 39
  Honduras: 40
  Hungary: 41
  India: 42
  Indonesia: 43
  Iraq: 44
  Ireland: 45
  Italy: 46
  Jamaica: 47
  Japan: 48
  Kazakhstan: 49
  Kenya: 50
  Latvia: 51
  Lebanon: 52
  Lesotho: 53
  Libya: 54
  Lithuania: 55
  Madagascar: 56
  Malawi: 57
  Malaysia: 58
  Mali: 59
  Mauritania: 60
  Mauritius: 61
  Mexico: 62
  Montenegro: 63
  Morocco: 64
  Mozambique: 65
  Namibia: 66
  Nepal: 67
  Netherlands: 68
  New Zealand: 69
  Nicaragua: 70
  Niger: 71
  Norway: 72
  Pakistan: 73
  Papua New Guinea: 74
  Peru: 75
  Poland: 76
  Portugal: 77
  Qatar: 78
  Romania: 79
  Rwanda: 80
  Saudi Arabia: 81
  Senegal: 82
  Slovenia: 83
  South Africa: 84
  Spain: 85
  Sri Lanka: 86
  Sudan: 87
  Suriname: 88
  Sweden: 89
  Switzerland: 90
  Tajikistan: 91
  Thailand: 92
  Tunisia: 93
  Turkey: 94
  Uganda: 95
  Ukraine: 96
  United Kingdom: 97
  Uruguay: 98
  Zambia: 99
  Zimbabwe: 100


# Set train/test split
test_size: 0.20

# Set the random seed
random_state: 42

# Alogrithm parameters
n_estimators: 100
max_depth: 10